function generateImage() {

    const canvas = document.getElementById("previewCanvas");
    const ctx = canvas.getContext("2d");

    const name = document.getElementById("name").value;
    const contactName = document.getElementById("contactName").value;
    const contactNumber = document.getElementById("contactNumber").value;
    const allergies = document.getElementById("allergies").value;
    const conditions = document.getElementById("conditions").value;

    // Background
    ctx.fillStyle = "#f4f8f9";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#1f4e5f";

    // Title
    ctx.font = "bold 28px Arial";
    ctx.textAlign = "center";
    ctx.fillText(name, canvas.width / 2, 120);

    ctx.font = "20px Arial";
    ctx.fillText("If I cannot speak, please call:", canvas.width / 2, 180);

    ctx.font = "bold 22px Arial";
    ctx.fillText(contactName, canvas.width / 2, 240);
    ctx.fillText(contactNumber, canvas.width / 2, 280);

    ctx.font = "18px Arial";

    if (allergies) {
        ctx.fillText("Allergy: " + allergies, canvas.width / 2, 340);
    }

    if (conditions) {
        ctx.fillText("Condition: " + conditions, canvas.width / 2, 380);
    }

    ctx.font = "14px Arial";
    ctx.fillText("Generated by Talk4.me", canvas.width / 2, 650);

    // Enable download
    const link = document.getElementById("downloadLink");
    link.href = canvas.toDataURL("image/png");
    link.download = "Talk4Me-LockScreen.png";
    link.innerHTML = "Download Lock Screen";
    link.style.display = "inline-block";
}
